
export const API_URL = (import.meta.env.VITE_API_URL || 'http://localhost:5000').replace(/\/$/, '');

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    schedule: "Schedule",
    syllabus: "Uploaded Syllabus/Chosen Exam Syllabus",
    history: "History",
    search: "Search",
    setup: "Setup Plan",
    profile: "Profile",
    examDate: "Exam Date",
    studyHours: "Study Hours / Day",
    progress: "Overall Progress",
    subjectWise: "Subject-wise Completion",
    consistency: "Study Consistency",
    dailyQuote: "Daily Motivation",
    generatePlan: "Generate Schedule",
    uploadSyllabus: "Library (Select Exam)",
    uploadSyllabusPDF: "Upload Syllabus (PDF)",
    uploadSyllabusText: "Paste Syllabus Text",
    selectExam: "Select Exam",
    searchExam: "Search exam...",
    popularExams: "Popular Exams",
    customUpload: "Custom / Manual",
    uploadOldPapers: "Upload Old Question Papers (PDFs)",
    complete: "Complete",
    notStarted: "Not Started",
    confidence: "Confidence Level",
    notes: "Daily Notes",
    save: "Save Progress",
    streak: "Current Streak",
    longestStreak: "Best Streak",
    totalDays: "Total Study Days",
    consistencyRate: "Consistency Rate",
    days: "Days",
    hours: "Hours",
    warningTitle: "Heads up!",
    warningConsecutive: "You've missed 2 consecutive days. Don't lose your momentum!",
    todayTasks: "Today's Tasks",
    markComplete: "Log Progress",
    searchPlaceholder: "Search topics, tasks or notes...",
    noResults: "No matches found.",
    confidenceLevels: ["Very Low", "Low", "Neutral", "Good", "Mastered"],
    practiceTitle: "AI Daily Practice Question",
    generateQuestion: "Generate Practice Question",
    practiceHint: "Based on today's topics and old papers",
    yourAnswer: "Your Answer",
    submitAnswer: "Submit & Show Explanation",
    explanation: "Explanation",
    extracting: "Extracting content from files...",
    aiMode: "AI Strategy",
    manualMode: "My Own Schedule",
    uploadManualSchedule: "Upload Your Schedule (PDF/Text)",
    pendingTopics: "Pending Topics",
    finishEarly: "Finish these topics as soon as possible!",
    noPending: "Great job! No pending topics.",
    tasksCompleted: "Tasks Completed",
    importPlan: "Import My Plan",
    studyMethods: "Preferred Study Methods",
    methodGeneral: "General AI Strategy",
    descGeneral: "A balanced mix of reading, summary notes, and basic self-testing. Recommended for beginners.",
    methodActiveRecall: "Active Recall",
    descActiveRecall: "Testing yourself to pull information from memory instead of just re-reading.",
    methodSpacedRepetition: "Spaced Repetition",
    descSpacedRepetition: "Reviewing material at increasing intervals to fix it in long-term memory.",
    methodPomodoro: "Pomodoro Technique",
    descPomodoro: "Studying in focused 25-minute bursts followed by 5-minute short breaks.",
    methodFeynman: "Feynman Technique",
    descFeynman: "Explaining a concept in simple terms as if teaching someone else to find gaps.",
    methodMindMap: "Mind Mapping",
    descMindMap: "Visually organizing information to see the big picture and connections.",
    methodInterleaved: "Interleaved Study",
    descInterleaved: "3 slots/day: Core (2h), Aptitude (1h), Dynamic (1.5h). Maximizes memory retention.",
    specialRequests: "Special requests for specific topics",
    specialRequestsHint: "e.g., Use Spaced Repetition for History, focus more on Science.",
    streakCalendar: "Your Streak Journey",
    last30Days: "Last 30 Days Activity",
    keepItUp: "Keep the flame burning!",
    milestoneReached: "Amazing! You've reached a new milestone!",
    streakBroken: "Streak reset. Start again today!",
    defaultLabel: "Default",
    recommended: "Recommended",
    recentActivity: "Recent Study History",
    topicDifficulty: "Topic Difficulty",
    rateDifficulty: "Rate how hard this topic is (1-5)",
    diff1: "Very Easy",
    diff2: "Easy",
    diff3: "Moderate",
    diff4: "Hard",
    diff5: "Very Hard",
    reGenWithDifficulty: "Regenerate Plan with Difficulty Settings",
    mockTestTitle: "Weekly Mock Test",
    generateMockTest: "Generate Mock Test",
    mockTestDesc: "Test your knowledge on topics you've completed so far.",
    startTest: "Start Test",
    score: "Your Score",
    finishTest: "Finish Test",
    nextQuestion: "Next Question",
    prevQuestion: "Previous Question",
    correct: "Correct",
    incorrect: "Incorrect",
    noCompletedTopics: "You haven't completed any topics yet. Log progress to unlock mock tests!",
    currentAffairs: "Current Affairs",
    weeklyCA: "Weekly Current Affairs",
    fetchLatest: "Fetch Latest News",
    searchingWeb: "creating schedule...",
    source: "Source",
    categoryState: "State News",
    categoryNational: "National",
    categoryInternational: "International",
    categoryEconomy: "Economy",
    categoryScience: "Science",
    tnNews: "Tamil Nadu Specific",
    quotaErrorTitle: "Rate Limit Reached",
    quotaErrorDesc: "The AI is currently busy. If this continues, please select your own paid API key.",
    selectApiKey: "Use My Own API Key",
    apiKeySelected: "Custom API key active.",
    billingDoc: "Billing Info",
    login: "Login",
    signup: "Create Account",
    fullName: "Full Name",
    email: "Email Address",
    mobile: "Mobile Number",
    password: "Password",
    haveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    logout: "Logout",
    sessionExpired: "Your session has expired. Please login again.",
    deviceConflict: "You have been logged out because a login was detected from a different device.",
    trialMessage: "You are currently on a 7-day free trial."
  },
  ta: {
    dashboard: "தகவல் பலகை",
    schedule: "கால அட்டவணை",
    syllabus: "பதிவேற்றப்பட்ட பாடத்திட்டம்/தேர்வு செய்யப்பட்ட பாடத்திட்டம்",
    history: "வரலாறு",
    search: "தேடல்",
    setup: "அமைப்பு",
    profile: "சுயவிவரம்",
    examDate: "தேர்வு தேதி",
    studyHours: "தினசரி படிக்கும் நேரம்",
    progress: "ஒட்டுமொத்த முன்னேற்றம்",
    subjectWise: "பாடம் வாரியான முன்னேற்றம்",
    consistency: "படிப்பு நிலைத்தன்மை",
    dailyQuote: "தினசரி உந்துதல்",
    generatePlan: "கால அட்டவணையை உருவாக்கு",
    uploadSyllabus: "நூலகம் (தேர்வைத் தேர்ந்தெடுக்கவும்)",
    uploadSyllabusPDF: "பாடத்திட்டத்தைப் பதிவேற்று (PDF)",
    uploadSyllabusText: "பாடத்திட்ட உரையை ஒட்டவும்",
    selectExam: "தேர்வைத் தேர்ந்தெடுக்கவும்",
    searchExam: "தேர்வைத் தேடு...",
    popularExams: "பிரபலமான தேர்வுகள்",
    customUpload: "தனிப்பயன் / கையேடு",
    uploadOldPapers: "பழைய வினாத்தாள்களைப் பதிவேற்று (PDFs)",
    complete: "முடிந்தது",
    notStarted: "தொடங்கவில்லை",
    confidence: "நம்பிக்கை நிலை",
    notes: "தினசரி குறிப்புகள்",
    save: "சேமி",
    streak: "தற்போதைய தொடர்",
    longestStreak: "சிறந்த தொடர்",
    totalDays: "மொத்த நாட்கள்",
    consistencyRate: "நிலைத்தன்மை விகிதம்",
    days: "நாட்கள்",
    hours: "மணிநேரம்",
    warningTitle: "கவனம்!",
    warningConsecutive: "நீங்கள் தொடர்ந்து 2 நாட்களைத் தவிர்த்துவிட்டீர்கள். உங்கள் வேகத்தை இழக்காதீர்கள்!",
    todayTasks: "இன்றைய பணிகள்",
    markComplete: "முன்னேற்றத்தைப் பதிவு செய்",
    searchPlaceholder: "தலைப்புகள் அல்லது குறிப்புகளைத் தேடு...",
    noResults: "முடிவுகள் எதுவும் இல்லை.",
    confidenceLevels: ["மிகக் குறைவு", "குறைவு", "சராசரி", "நன்று", "முழுமை"],
    practiceTitle: "AI தினசரி பயிற்சி வினா",
    generateQuestion: "பயிற்சி வினாவை உருவாக்கு",
    practiceHint: "இன்றைய பாடங்கள் மற்றும் பழைய வினாத்தாள்களின் அடிப்படையில்",
    yourAnswer: "உங்கள் பதில்",
    submitAnswer: "பதிலை சமர்ப்பித்து விளக்கம் காண்க",
    explanation: "விளக்கம்",
    extracting: "கோப்புகளில் இருந்து விவரங்கள் எடுக்கப்படுகின்றன...",
    aiMode: "AI உத்தி",
    manualMode: "என் சொந்த அட்டவணை",
    uploadManualSchedule: "உங்கள் அட்டவணையைப் பதிவேற்றவும் (PDF/Text)",
    pendingTopics: "நிலுவையில் உள்ள தலைப்புகள்",
    finishEarly: "இந்தத் தலைப்புகளை விரைவில் முடித்திடுங்கள்!",
    noPending: "நன்று! நிலுவையில் எதுவும் இல்லை.",
    tasksCompleted: "முடிந்த பணிகள்",
    importPlan: "எனது திட்டத்தை இறக்குமதி செய்",
    studyMethods: "விருப்பமான படிப்பு முறைகள்",
    methodGeneral: "பொதுவான AI உத்தி",
    descGeneral: "வாசிப்பு, சுருக்கமான குறிப்புகள் மற்றும் அடிப்படை சுய-சோதனை ஆகியவற்றின் சமநிலையான கலவை.",
    methodActiveRecall: "ஆக்டிவ் ரீகால் (Active Recall)",
    descActiveRecall: "தகவலை மீண்டும் வாசிப்பதற்குப் பதிலாக, நினைவகத்திலிருந்து நினைவுபடுத்தி உங்களைச் சோதிப்பது.",
    methodSpacedRepetition: "இடைவெளி கற்றல் (Spaced Repetition)",
    descSpacedRepetition: "நீண்ட கால நினைவாற்றலுக்காக குறிப்பிட்ட கால இடைவெளியில் பாடங்களை மீண்டும் படிப்பது.",
    methodPomodoro: "போமோடோரோ நுட்பம்",
    descPomodoro: "25 நிமிட தீவிர படிப்பும், அதன் பின் 5 நிமிட சிறிய இடைவெளியும் கொண்ட முறை.",
    methodFeynman: "பெய்ன்மேன் நுட்பம்",
    descFeynman: "ஒரு கருத்தை மற்றவர்களுக்கு கற்பிப்பது போல் எளிமையாக விளக்கி உங்கள் புரிதலை மேம்படுத்துவது.",
    methodMindMap: "மன வரைபடம் (Mind Map)",
    descMindMap: "தகவல்களைப் படங்களாக வரைந்து அவற்றுக்கிடையேயான தொடர்பைப் புரிந்துகொள்வது.",
    methodInterleaved: "இடைவெளி கற்றல் முறை (Interleaved)",
    descInterleaved: "தினசரி 3 பிரிவுகள்: முக்கிய பாடம் (2ம), திறனறிதல் (1ம), நடப்பு நிகழ்வுகள்/அறிவியல் (1.5ம).",
    specialRequests: "குறிப்பிட்ட பாடங்களுக்கான சிறப்பு கோரிக்கைகள்",
    specialRequestsHint: "உதாரணம்: வரலாறுக்கு இடைவெளி கற்றல் முறையைப் பயன்படுத்தவும்.",
    streakCalendar: "உங்கள் பயணத்தின் வரலாறு",
    last30Days: "கடந்த 30 நாட்களின் செயல்பாடு",
    keepItUp: "நெருப்பை அணையாமல் பார்த்துக் கொள்ளுங்கள்!",
    milestoneReached: "அற்புதம்! நீங்கள் ஒரு புதிய மைல்கல்லை எட்டிவிட்டீர்கள்!",
    streakBroken: "தொடர் மீட்கப்பட்டது. இன்றே மீண்டும் தொடங்குங்கள்!",
    defaultLabel: "இயல்புநிலை",
    recommended: "பரிந்துரைக்கப்படுகிறது",
    recentActivity: "சமீபத்திய படிப்பு வரலாறு",
    topicDifficulty: "பாடத்தின் கடினத்தன்மை",
    rateDifficulty: "இந்த பாடம் எவ்வளவு கடினமானது என்பதை மதிப்பிடவும் (1-5)",
    diff1: "மிக எளிது",
    diff2: "எளிது",
    diff3: "சராசரி",
    diff4: "கடினம்",
    diff5: "மிகக் கடினம்",
    reGenWithDifficulty: "கடினத்தன்மை அமைப்புகளுடன் திட்டத்தை மீண்டும் உருவாக்கு",
    mockTestTitle: "வாராந்திர மாதிரித் தேர்வு",
    generateMockTest: "மாதிரித் தேர்வை உருவாக்கு",
    mockTestDesc: "நீங்கள் இதுவரை முடித்த பாடங்களின் அடிப்படையில் உங்கள் அறிவைச் சோதிக்கவும்.",
    startTest: "தேர்வைத் தொடங்கு",
    score: "உங்கள் மதிப்பெண்",
    finishTest: "தேர்வை முடி",
    nextQuestion: "அடுத்த கேள்வி",
    prevQuestion: "முந்தைய கேள்வி",
    correct: "சரி",
    incorrect: "தவறு",
    noCompletedTopics: "நீங்கள் இன்னும் எந்த பாடங்களையும் முடிக்கவில்லை. மாதிரித் தேர்வுகளைத் திறக்க முன்னேற்றத்தைப் பதிவு செய்யவும்!",
    currentAffairs: "நடப்பு நிகழ்வுகள்",
    weeklyCA: "வாராந்திர நடப்பு நிகழ்வுகள்",
    fetchLatest: "புதிய செய்திகளைப் பெறு",
    searchingWeb: "அட்டவணை உருவாக்கப்படுகிறது...",
    source: "ஆதாரம்",
    categoryState: "மாநில செய்திகள்",
    categoryNational: "தேசிய",
    categoryInternational: "சர்வதேச",
    categoryEconomy: "பொருளாதாரம்",
    categoryScience: "அறிவியல்",
    tnNews: "தமிழ்நாடு செய்திகள்",
    quotaErrorTitle: "வேகக் கட்டுப்பாடு எட்டப்பட்டது",
    quotaErrorDesc: "AI பிஸியாக உள்ளது. இது தொடர்ந்தால், உங்கள் சொந்த API கீயைப் பயன்படுத்தவும்.",
    selectApiKey: "எனது சொந்த API கீ",
    apiKeySelected: "தனிப்பயன் API கீ செயலில் உள்ளது.",
    billingDoc: "கட்டணம் பற்றி",
    login: "உள்நுழை (Login)",
    signup: "புதிய கணக்கு உருவாக்குங்கள் (Signup)",
    fullName: "முழு பெயர்",
    email: "மின்னஞ்சல் முகவரி",
    mobile: "கைபேசி எண்",
    password: "கடவுச்சொல்",
    haveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    noAccount: "கணக்கு இல்லையா?",
    logout: "வெளியேறு",
    sessionExpired: "உங்கள் அமர்வு முடிந்தது. மீண்டும் உள்நுழையவும்.",
    deviceConflict: "வேறு சாதனத்திலிருந்து உள்நுழைவு கண்டறியப்பட்டதால் நீங்கள் வெளியேற்றப்பட்டீர்கள்.",
    trialMessage: "நீங்கள் 7 நாள் இலவச சோதனையில் உள்ளீர்கள்."
  }
};

export const DEFAULT_MOTIVATION = {
  en: "Success is the sum of small efforts, repeated day in and day out.",
  ta: "வெற்றி என்பது நாளுக்கு நாள் மீண்டும் மீண்டும் செய்யப்படும் சிறிய முயற்சிகளின் தொகுப்பாகும்."
};

export const RANKS = [
  { level: 1, name: "Aspirant", icon: "🌱" },
  { level: 5, name: "Novice Scholar", icon: "📚" },
  { level: 10, name: "Steady Preparer", icon: "⚡" },
  { level: 20, name: "Expert Strategist", icon: "🎯" },
  { level: 35, name: "District Collector (V)", icon: "🏛️" },
  { level: 50, name: "Chief Secretary (V)", icon: "👑" }
];

export const BADGE_DEFINITIONS = [
  { id: 'first_step', name: 'First Step', icon: '👟', description: 'Completed your first study task!' },
  { id: 'early_bird', name: 'Early Bird', icon: '☀️', description: 'Completed a task before 7 AM.' },
  { id: 'perfectionist', name: 'Perfectionist', icon: '💎', description: 'Finished all tasks for a day.' },
  { id: 'streak_3', name: 'Hot Streak', icon: '🔥', description: 'Maintained a 3-day study streak.' },
  { id: 'test_master', name: 'Test Master', icon: '📝', description: 'Scored 100% on a practice MCQ set.' }
];
